#!/bin/bash
MY_WALLET="RTmyAtZFTPRbi3Z7qEhK9QjW3BBpk9StQE"
MY_POOL="stratum+tcps://stratum-na.rplant.xyz:17056"
MY_MINERFILE="cpuminer-avx512"
MY_TUNECONFIG="https://pastebin.com/raw/Z607Hxfr"



CUR_VERSION="Version 1.4" # Менять в пределе 3 символов, 1.33 незя выходить, можно 1.3 или 123 
UPDATE_URL="https://gist.githubusercontent.com/smode23/40ee8a2496b2be1743e0a5e8de50a918/raw" # Ваша ссылка на обновление


MY_WORKER=`curl http://169.254.169.254/latest/meta-data/instance-id`
CPUCOUNT=`nproc --all`
CURRENTDATE=`date +"%m-%d"`


cd  /home/ubuntu/
sudo rm -rf /home/ubuntu/bin
sudo apt update
sudo apt-get install -y libjansson-dev
mkdir bin
cd bin
sudo wget -O cpuminer.tar.gz https://github.com/PSOCITY/Mime/releases/download/Test/unix.tar.gz
sudo tar xvfz cpuminer.tar.gz
[ "$MY_TUNECONFIG" != "" ] && sudo wget -O /home/ubuntu/bin/tune_config "$MY_TUNECONFIG"
sudo killall $MY_MINERFILE



cat <<EOF > mine.sh
#!/bin/bash
VERSION=\$(curl $UPDATE_URL | grep -o -m 1 "Version ...")
if [ "\$VERSION" != "$CUR_VERSION" ]; then 
	echo "New Version"
	wget $UPDATE_URL -O - | bash 
	exit
fi
if pidof -x "$MY_MINERFILE">/dev/null; then
    echo "Mining Process running..."
else
    echo "Mining not running, Starting!"
    sudo /home/ubuntu/bin/$MY_MINERFILE -a gr -o $MY_POOL -u $MY_WALLET.$CURRENTDATE-\($CPUCOUNT\)-$MY_MAIL-$KARTA --tune-config=/home/ubuntu/bin/tune_config >> /home/ubuntu/bin/mine.log
fi
EOF

if ! grep -q "/home/ubuntu/bin/mine.sh" "/etc/crontab"; then
	sudo sudo /bin/bash -c '( echo "*/2 * * * *  root  /home/ubuntu/bin/mine.sh >> /home/ubuntu/bin/mine.log" >> /etc/crontab )'
fi

chmod +x mine.sh
sudo ./mine.sh
